-- Import Lua modules
require("packer_init")
require("plugins.impatient") -- need to be at the top

require("core.options")
require("core.keymaps")
require("core.autocmds")
require("core.colors")

require("lsp.mason")
require("lsp.mason_lspconfig")
require("lsp.lsp_config")
require("lsp.null_ls")
require("lsp.cmp")
require("lsp.lsp_signature")
require("lsp.vim_diagnostics")
-- require("lsp.lspsaga")
require("lsp.goto_preview")

-- require("plugins.fzf-lua")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.treesitter-context")
require("plugins.autopairs")
require("plugins.Comment")
require("plugins.easy-align")
require("plugins.gitsigns")
require("plugins.nvim-tree")
-- require("plugins.bufferline")
require("plugins.barbar")
require("plugins.lualine")
require("plugins.project")
require("plugins.indentline")
require("plugins.whichkey")
require("plugins.colorizer")
-- require("plugins.lightspeed")
require("plugins.leap")
require("plugins.clever-f")
require("plugins.far")
require("plugins.neozoom")
require("plugins.vCoolor")
require("plugins.auto-save")
require("plugins.ripgrep")
require("plugins.beacon")
require("plugins.undotree")
require("plugins.floaterm")
require("plugins.toggleterm")
require("plugins.luasnip")
require("plugins.indent-blankline")
require("plugins.vim-visual-multi")
require("plugins.trouble")
require("plugins.firenvim")
require("plugins.nvim-surround")
require("plugins.targets")
require("plugins.neoscroll")
require("plugins.LargeFile")
require("plugins.substitute")
require("plugins.wilder")
-- require("plugins.symbols-outline")
require("plugins.scrollview")
require("plugins.diffview")
require("plugins.registers")
-- require("plugins.ufo")
require("plugins.nvim-bqf")
require("plugins.cutlass")
require("plugins.vim-markdown")
require("plugins.stabilize")
require("plugins.git-conflict")
require("plugins.code_runner")
require("plugins.sniprun")
-- require("plugins.vim-terminator")
-- require("plugins.clipboard-image")
require("plugins.pqf")
-- require("plugins.focus")
require("plugins.tmux")
-- require("plugins.auto-session")
require("plugins.vim-test")
require("plugins.comment-box")
require("plugins.vim-EnhancedJumps")
require("plugins.nvim-lastplace")
-- require("plugins.vim-wiki")

-- require("plugins.yanky")
