require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.Comment")
require("user.gitsigns")
require("user.nvim-tree")
-- require("user.barbar")
require("user.bufferline")
require("user.lualine")
require("user.project")
require("user.impatient")
require("user.indentline")
-- require("user.alpha")
require("user.whichkey")
require("user.autocommands")
require("user.colorizer")
require("user.lightspeed")
-- require("user.surround")
-- require "user.autosession"
require("user.ripgrep")
require("user.lastplace")
require("user.beacon")
-- require("user.autosave")
require("user.undotree")
require("user.executioner")
require("user.floaterm")
require("user.doom-one")
require("user.luasnip")
require("user.indent-blankline")
require("user.vim-visual-multi")
require("user.trouble")
-- require("user.hardtime")
require("user.firenvim")
require("user.sandwitch")
require("user.targets")
require("user.neoscroll")
require("user.better-escape")
require("user.substitute")
require("user.startify")
require("user.wilder")
require("user.symbols-outline")
require("user.scrollview")
-- require("user.sad")

-- require("user.typescript")
-- require("user.yanky") BUG?
-- require("user.cutlass") BUG?
-- require("user.yoink")
-- require("user.nvim-bqf")
